const fs = require('fs');
const path = require('path');

const p = path.join(__dirname, 'src', 'data', 'products.ts');
let content = fs.readFileSync(p, 'utf8');

// 1. Insert imports at the top
const imports = `import imgPhilipsHue from "@/assets/philips_hue_bulb_1780415335337.png";
import imgYandexBtn from "@/assets/yandex_smart_button_1780415349203.png";
import imgSunricherDaliDt8 from "@/assets/sunricher_dali_dt8_1780415374155.png";
import imgSunricherKnxDali from "@/assets/sunricher_knx_dali_1780415387464.png";
import imgSunricherZigbeeDimmer from "@/assets/sunricher_zigbee_dimmer_1780415398202.png";
import imgSunricherDaliPower from "@/assets/sunricher_dali_power_1780415409665.png";
import imgSunricherKnxSwitch from "@/assets/sunricher_knx_switch_1780415430474.png";
import imgSunricherZigbeeStrip from "@/assets/sunricher_zigbee_strip_1780415442836.png";
import imgSunricherDaliCoupler from "@/assets/sunricher_dali_coupler_1780415457009.png";
import imgSunricher010vDimmer from "@/assets/sunricher_010v_dimmer_1780415467411.png";
import imgSunricherDaliPanel from "@/assets/sunricher_dali_panel_1780415479882.png";
import imgSunricherKnxDimmer from "@/assets/sunricher_knx_dimmer_1780415499657.png";
import imgIridiServerUmc from "@/assets/iridi_server_umc_1780415510494.png";
import imgIridiKnxServer from "@/assets/iridi_knx_server_1780415526832.png";
import imgIridiRelay8ch from "@/assets/iridi_relay_8ch_1780415538533.png";
import imgIridiDimmer4ch from "@/assets/iridi_dimmer_4ch_1780415553095.png";
`;

content = imports + content;

// 2. Add to images object
const imagesAdditions = `
  imgPhilipsHue,
  imgYandexBtn,
  imgSunricherDaliDt8,
  imgSunricherKnxDali,
  imgSunricherZigbeeDimmer,
  imgSunricherDaliPower,
  imgSunricherKnxSwitch,
  imgSunricherZigbeeStrip,
  imgSunricherDaliCoupler,
  imgSunricher010vDimmer,
  imgSunricherDaliPanel,
  imgSunricherKnxDimmer,
  imgIridiServerUmc,
  imgIridiKnxServer,
  imgIridiRelay8ch,
  imgIridiDimmer4ch,
  imgIridiIo16ch: "https://iridi.com/images/equipment/pro/umc.png", // fallback realistic images since quota hit
  imgAqaraRelayT2: "https://www.aqara.com/wp-content/uploads/2023/07/Dual-Relay-Module-T2.png",
  imgAqaraSwitchT1: "https://www.aqara.com/wp-content/uploads/2023/04/SSM-U01-1.png",
  imgMeanWellKnx: "https://www.meanwell.com/Upload/PDF/KNX-20E-640/KNX-20E-640-spec.pdf", // placeholder
  imgZennioMaxinbox: "https://www.zennio.com/images/productos/maxinbox-16-plus-v2/ZIO-MB16PLUSV2_front.png",
  imgWirenBoard7: "https://wirenboard.com/img/catalog/wb7/wb7_main.png",
`;
content = content.replace('const images = {', 'const images = {' + imagesAdditions);

// 3. Update existing Hue and Yandex items
// For Philips Hue:
content = content.replace(
  /slug:\s*"philips-hue-white-color-ambiance-a19",[\s\S]*?image:\s*images\.philipsHueBulb,/,
  match => match.replace('images.philipsHueBulb', 'images.imgPhilipsHue')
);

// For Yandex Button:
content = content.replace(
  /slug:\s*"yandex-smart-button",[\s\S]*?image:\s*images\.yandexAlice,/,
  match => match.replace('images.yandexAlice', 'images.imgYandexBtn')
);

// 4. Add 20 new products to productSeeds
const newProducts = `
  {
    slug: "sunricher-dali2-dt8-led-controller",
    name: "Sunricher DALI-2 DT8 LED Controller (SR-2309PRO)",
    brand: "Sunricher",
    group: "b2b",
    collection: "Professional · Control",
    tagline: "Диммер для управления RGBW лентами по протоколу DALI",
    description: "Профессиональный 4-канальный диммер с поддержкой протокола DALI-2 DT8 для управления цветным освещением и цветовой температурой.",
    category: "relays-actuators",
    categoryLabel: "Реле и модули",
    subcategory: "din-dimmers",
    subcategoryLabel: "DIN-реечные диммеры",
    price: 27000,
    rating: 4.8,
    reviewsCount: 32,
    image: images.imgSunricherDaliDt8,
    protocols: ["DALI-2"],
    functions: ["Диммирование", "RGBW контроль"],
    compatibility: ["DALI Systems", "KNX to DALI Gateways"],
    sourceUrl: "https://www.sunricher.com",
    specs: { "Каналы": "4CH", "Напряжение": "12-36V DC" },
    primaryFeature: "DT8 Протокол",
    featureText: "Управление цветом и яркостью по одному DALI-адресу."
  },
  {
    slug: "sunricher-knx-dali-gateway",
    name: "Sunricher KNX to DALI Gateway (SR-KNX-DALI)",
    brand: "Sunricher",
    group: "b2b",
    collection: "Professional · Gateways",
    tagline: "Шлюз для интеграции освещения DALI в шину KNX",
    description: "Позволяет полноценно интегрировать до 64 DALI устройств в системы автоматизации на базе стандарта KNX.",
    category: "gateways-protocols",
    categoryLabel: "Шлюзы и протоколы",
    subcategory: "dali-gateways",
    subcategoryLabel: "Шлюзы DALI",
    price: 135000,
    rating: 4.9,
    reviewsCount: 15,
    image: images.imgSunricherKnxDali,
    protocols: ["KNX", "DALI"],
    functions: ["Интеграция", "Маршрутизация", "Контроль света"],
    compatibility: ["KNX", "DALI"],
    sourceUrl: "https://www.sunricher.com",
    specs: { "Поддержка": "до 64 DALI ЭПРА", "Питание": "От шины KNX / 230V" },
    primaryFeature: "Бесшовная интеграция",
    featureText: "Связывает корпоративный стандарт KNX с профессиональным светом DALI."
  },
  {
    slug: "sunricher-zigbee-ac-phase-cut-dimmer",
    name: "Sunricher Zigbee AC Phase Cut Dimmer (SR-ZG9101SAC)",
    brand: "Sunricher",
    group: "b2b",
    collection: "Professional · Dimmers",
    tagline: "Встраиваемый диммер для классических ламп",
    description: "Диммер с фазовой отсечкой (Trailing/Leading Edge) для управления классическими 230V LED и лампами накаливания по Zigbee 3.0.",
    category: "relays-actuators",
    categoryLabel: "Реле и модули",
    subcategory: "embedded-relays",
    subcategoryLabel: "Встраиваемые реле",
    price: 18000,
    rating: 4.7,
    reviewsCount: 45,
    image: images.imgSunricherZigbeeDimmer,
    protocols: ["Zigbee 3.0"],
    functions: ["Диммирование", "Фазовая отсечка"],
    compatibility: ["Zigbee HA", "Matter via Hub", "Philips Hue"],
    sourceUrl: "https://www.sunricher.com",
    specs: { "Нагрузка": "до 400W", "Монтаж": "В подрозетник" },
    primaryFeature: "Универсальное диммирование",
    featureText: "Поддерживает как передний, так и задний фронт."
  },
  {
    slug: "sunricher-dali-power-supply-250ma",
    name: "Sunricher DALI Power Supply 250mA (SR-2400P)",
    brand: "Sunricher",
    group: "b2b",
    collection: "Professional · Power",
    tagline: "Профессиональный блок питания для шины DALI",
    description: "Обеспечивает стабильное питание 16V DC для шины DALI с током до 250мА (до 128 устройств).",
    category: "bus-systems",
    categoryLabel: "Шинные системы",
    subcategory: "bus-power",
    subcategoryLabel: "Блоки питания для шины",
    price: 31500,
    rating: 4.9,
    reviewsCount: 11,
    image: images.imgSunricherDaliPower,
    protocols: ["DALI"],
    functions: ["Питание шины"],
    compatibility: ["DALI"],
    sourceUrl: "https://www.sunricher.com",
    specs: { "Выход": "16V DC 250mA", "Защита": "От КЗ и перегрузки" },
    primaryFeature: "Надежность",
    featureText: "Гарантирует стабильную работу длинных DALI-линий."
  },
  {
    slug: "sunricher-4ch-knx-switch",
    name: "Sunricher 4-Channel KNX Switch Actuator",
    brand: "Sunricher",
    group: "b2b",
    collection: "Professional · KNX",
    tagline: "4-канальное реле на DIN-рейку для управления силовыми нагрузками",
    description: "Надежный актуатор KNX для коммутации цепей освещения, розеток или отопления с поддержкой логики.",
    category: "relays-actuators",
    categoryLabel: "Реле и модули",
    subcategory: "din-relays",
    subcategoryLabel: "DIN-реечные реле",
    price: 81000,
    rating: 4.8,
    reviewsCount: 22,
    image: images.imgSunricherKnxSwitch,
    protocols: ["KNX"],
    functions: ["Коммутация", "Логика", "Сценарии"],
    compatibility: ["KNX"],
    sourceUrl: "https://www.sunricher.com",
    specs: { "Каналы": "4x 16A", "Монтаж": "DIN-рейка" },
    primaryFeature: "Высокая нагрузка",
    featureText: "Справляется со стартовыми токами емкостных нагрузок."
  },
  {
    slug: "sunricher-zigbee-led-strip-controller",
    name: "Sunricher Zigbee LED Strip Controller (RGB+CCT)",
    brand: "Sunricher",
    group: "b2b",
    collection: "Professional · Control",
    tagline: "Контроллер светодиодных лент для экосистемы Zigbee 3.0",
    description: "Профессиональный 5-канальный контроллер (RGB + CCT) для создания сложного архитектурного света.",
    category: "relays-actuators",
    categoryLabel: "Реле и модули",
    subcategory: "din-dimmers",
    subcategoryLabel: "ШИМ контроллеры",
    price: 22500,
    rating: 4.9,
    reviewsCount: 68,
    image: images.imgSunricherZigbeeStrip,
    protocols: ["Zigbee 3.0"],
    functions: ["Управление лентами", "RGBW+CCT"],
    compatibility: ["Zigbee", "Philips Hue", "Home Assistant"],
    sourceUrl: "https://www.sunricher.com",
    specs: { "Выход": "5x 4A", "Питание": "12-24V DC" },
    primaryFeature: "Плавность диммирования",
    featureText: "Глубокое и плавное изменение яркости без мерцания на камеру."
  },
  {
    slug: "sunricher-dali-push-button-coupler",
    name: "Sunricher DALI Push Button Coupler (SR-2402K4)",
    brand: "Sunricher",
    group: "b2b",
    collection: "Professional · Interfaces",
    tagline: "Модуль сопряжения (сухой контакт) для выключателей",
    description: "Превращает любую классическую кнопочную панель (до 4 клавиш) в полноправный элемент сети DALI.",
    category: "relays-actuators",
    categoryLabel: "Реле и модули",
    subcategory: "embedded-relays",
    subcategoryLabel: "Встраиваемые интерфейсы",
    price: 18000,
    rating: 4.6,
    reviewsCount: 19,
    image: images.imgSunricherDaliCoupler,
    protocols: ["DALI"],
    functions: ["Ввод", "Сценарии"],
    compatibility: ["DALI"],
    sourceUrl: "https://www.sunricher.com",
    specs: { "Входы": "4 сухих контакта", "Питание": "От шины DALI" },
    primaryFeature: "Скрытый монтаж",
    featureText: "Умещается за обычным выключателем в подрозетнике."
  },
  {
    slug: "sunricher-0-10v-zigbee-dimmer",
    name: "Sunricher 0/1-10V Zigbee Dimmer",
    brand: "Sunricher",
    group: "b2b",
    collection: "Professional · Dimmers",
    tagline: "Диммер для светильников с аналоговым управлением 0-10V",
    description: "Интегрирует профессиональные светильники с драйверами 0-10V или 1-10V в экосистему умного дома Zigbee.",
    category: "relays-actuators",
    categoryLabel: "Реле и модули",
    subcategory: "din-dimmers",
    subcategoryLabel: "Контроллеры 0-10V",
    price: 20250,
    rating: 4.7,
    reviewsCount: 27,
    image: images.imgSunricher010vDimmer,
    protocols: ["Zigbee 3.0", "0/1-10V"],
    functions: ["Аналоговое диммирование", "Управление драйверами"],
    compatibility: ["Zigbee", "Аналоговые драйверы"],
    sourceUrl: "https://www.sunricher.com",
    specs: { "Выход": "Сигнал 0-10V", "Реле": "Встроенное" },
    primaryFeature: "Совместимость с PRO-светом",
    featureText: "Управляет тяжелыми промышленными и офисными светильниками."
  },
  {
    slug: "sunricher-dali-wall-touch-panel",
    name: "Sunricher DALI Wall Touch Panel (Стекло)",
    brand: "Sunricher",
    group: "b2b",
    collection: "Professional · Control",
    tagline: "Настенная 4-зонная сенсорная панель управления светом",
    description: "Стеклянная DALI-панель премиум класса для управления 4 группами света или сценами без внешнего контроллера.",
    category: "bus-systems",
    categoryLabel: "Шинные системы",
    subcategory: "bus-sensors-switches",
    subcategoryLabel: "Шинные выключатели",
    price: 54000,
    rating: 4.8,
    reviewsCount: 12,
    image: images.imgSunricherDaliPanel,
    protocols: ["DALI"],
    functions: ["Интерфейс пользователя", "Сценарии"],
    compatibility: ["DALI"],
    sourceUrl: "https://www.sunricher.com",
    specs: { "Зоны": "4", "Материал": "Закаленное стекло" },
    primaryFeature: "DALI Master",
    featureText: "Может работать автономно как мастер на шине DALI."
  },
  {
    slug: "sunricher-knx-dimmer-actuator",
    name: "Sunricher KNX Universal Dimmer Actuator 4-Fold",
    brand: "Sunricher",
    group: "b2b",
    collection: "Professional · KNX",
    tagline: "4-канальный универсальный диммер на DIN-рейку для KNX",
    description: "Мощный актуатор для диммирования галогенных, LED и ламп накаливания в проектах автоматизации KNX.",
    category: "relays-actuators",
    categoryLabel: "Реле и модули",
    subcategory: "din-dimmers",
    subcategoryLabel: "DIN-реечные диммеры",
    price: 112500,
    rating: 4.9,
    reviewsCount: 29,
    image: images.imgSunricherKnxDimmer,
    protocols: ["KNX"],
    functions: ["Фазовое диммирование", "Управление светом"],
    compatibility: ["KNX"],
    sourceUrl: "https://www.sunricher.com",
    specs: { "Каналы": "4", "Авто-детекция": "Leading/Trailing edge" },
    primaryFeature: "Умное распознавание нагрузки",
    featureText: "Сам определяет тип подключенной лампы для идеального диммирования."
  },
  {
    slug: "iridi-server-umc",
    name: "iRidi Server UMC (Universal Controller)",
    brand: "iRidi",
    group: "b2b",
    collection: "Professional · Controllers",
    tagline: "Универсальный сервер автоматизации на DIN-рейку",
    description: "Мощное ядро умного дома. Объединяет десятки протоколов (Modbus, KNX, MQTT) и реализует сложную логику без облаков.",
    category: "hubs-networking",
    categoryLabel: "Хабы и серверы",
    subcategory: "multi-protocol-hubs",
    subcategoryLabel: "Серверы автоматизации",
    price: 270000,
    rating: 5.0,
    reviewsCount: 18,
    image: images.imgIridiServerUmc,
    protocols: ["KNX", "Modbus", "MQTT", "TCP/IP"],
    functions: ["Сервер логики", "Шлюз", "Платформа визуализации"],
    compatibility: ["iRidi Pro", "Большинство ПЛК"],
    sourceUrl: "https://iridi.com",
    specs: { "ОС": "Linux", "Интерфейсы": "RS-485, KNX, Ethernet" },
    primaryFeature: "Полная свобода интеграции",
    featureText: "Объединяет в одном проекте аудио, свет, климат и безопасность разных брендов."
  },
  {
    slug: "iridi-knx-home-server",
    name: "iRidi KNX Home Server",
    brand: "iRidi",
    group: "b2b",
    collection: "Professional · Controllers",
    tagline: "Сервер для визуализации и управления системами KNX",
    description: "Компактный сервер для быстрой развертки красивого интерфейса (мобильные панели) поверх инсталляций KNX.",
    category: "hubs-networking",
    categoryLabel: "Хабы и серверы",
    subcategory: "multi-protocol-hubs",
    subcategoryLabel: "Серверы автоматизации",
    price: 315000,
    rating: 4.8,
    reviewsCount: 24,
    image: images.imgIridiKnxServer,
    protocols: ["KNX", "TCP/IP"],
    functions: ["Визуализация KNX", "Сценарии"],
    compatibility: ["KNX TP1", "iRidi Pro"],
    sourceUrl: "https://iridi.com",
    specs: { "KNX": "Встроенный BAOS", "Питание": "PoE / 24V" },
    primaryFeature: "Интерфейс для KNX",
    featureText: "Делает сложную шину KNX понятной для конечного пользователя через приложение."
  },
  {
    slug: "iridi-relay-module-8ch",
    name: "iRidi Relay Module 8-Channel",
    brand: "iRidi",
    group: "b2b",
    collection: "Professional · Buspro",
    tagline: "8-канальный релейный модуль расширения",
    description: "Силовой модуль для щита. Управляет розетками, теплым полом, шторами или клапанами отопления.",
    category: "relays-actuators",
    categoryLabel: "Реле и модули",
    subcategory: "din-relays",
    subcategoryLabel: "DIN-реечные реле",
    price: 112500,
    rating: 4.7,
    reviewsCount: 33,
    image: images.imgIridiRelay8ch,
    protocols: ["Buspro", "RS-485"],
    functions: ["Коммутация", "Управление шторами"],
    compatibility: ["iRidi", "Modbus"],
    sourceUrl: "https://iridi.com",
    specs: { "Каналы": "8 x 16A", "Ручное управление": "Есть" },
    primaryFeature: "Взаимоблокировка",
    featureText: "Аппаратная поддержка режимов работы со шторами и приводами."
  },
  {
    slug: "iridi-dimmer-module-4ch",
    name: "iRidi Dimmer Module 4-Channel (TRIAC)",
    brand: "iRidi",
    group: "b2b",
    collection: "Professional · Buspro",
    tagline: "Модуль симисторного диммирования",
    description: "Обеспечивает ровное и беззвучное управление яркостью галогенных и LED ламп прямо из электрощита.",
    category: "relays-actuators",
    categoryLabel: "Реле и модули",
    subcategory: "din-dimmers",
    subcategoryLabel: "DIN-реечные диммеры",
    price: 135000,
    rating: 4.9,
    reviewsCount: 16,
    image: images.imgIridiDimmer4ch,
    protocols: ["Buspro"],
    functions: ["Симисторное диммирование"],
    compatibility: ["iRidi"],
    sourceUrl: "https://iridi.com",
    specs: { "Каналы": "4 x 1.5A", "Тип": "TRIAC" },
    primaryFeature: "Бесшумность",
    featureText: "Отсутствие акустического шума (гудения) при диммировании."
  },
  {
    slug: "iridi-io-module-16",
    name: "iRidi I/O Module (16 inputs)",
    brand: "iRidi",
    group: "b2b",
    collection: "Professional · Interfaces",
    tagline: "Модуль ввода для подключения датчиков и выключателей",
    description: "Сборщик сигналов типа сухой контакт. Идеален для подключения классических выключателей, датчиков протечки и герконов в умный дом.",
    category: "relays-actuators",
    categoryLabel: "Реле и модули",
    subcategory: "din-relays",
    subcategoryLabel: "Модули ввода",
    price: 90000,
    rating: 4.8,
    reviewsCount: 42,
    image: images.imgIridiIo16ch,
    protocols: ["Buspro", "RS-485"],
    functions: ["Сбор дискретных сигналов"],
    compatibility: ["iRidi"],
    sourceUrl: "https://iridi.com",
    specs: { "Входы": "16", "Выходы LED": "Есть (для индикации)" },
    primaryFeature: "Массовый сбор данных",
    featureText: "Один модуль оцифровывает весь дом."
  },
  {
    slug: "aqara-dual-relay-module-t2",
    name: "Aqara Dual Relay Module T2",
    brand: "Aqara",
    group: "b2b",
    collection: "Professional · Zigbee",
    tagline: "Двухканальное реле (сухой контакт) с мониторингом",
    description: "Многофункциональное реле. Поддерживает работу с сухими контактами (ворота, котлы) и питание от AC/DC. Монтаж на DIN-рейку или в подрозетник.",
    category: "relays-actuators",
    categoryLabel: "Реле и модули",
    subcategory: "embedded-relays",
    subcategoryLabel: "Встраиваемые реле",
    price: 13500,
    rating: 4.8,
    reviewsCount: 156,
    image: images.imgAqaraRelayT2,
    protocols: ["Zigbee 3.0", "Matter"],
    functions: ["Сухой контакт", "Реле", "Мониторинг энергии"],
    compatibility: ["Aqara Home", "Apple Home", "Matter"],
    sourceUrl: "https://www.aqara.com",
    specs: { "Монтаж": "DIN / Подрозетник", "Питание": "100-250V AC / 24-60V DC" },
    primaryFeature: "Универсальность",
    featureText: "Подходит для управления освещением, шлагбаумами и котлами."
  },
  {
    slug: "aqara-single-switch-module-t1",
    name: "Aqara Single Switch Module T1 (With Neutral)",
    brand: "Aqara",
    group: "b2b",
    collection: "Professional · Zigbee",
    tagline: "Встраиваемое реле с нейтралью",
    description: "Делает классический выключатель умным, сохраняя его функции. Поддерживает мониторинг энергопотребления.",
    category: "relays-actuators",
    categoryLabel: "Реле и модули",
    subcategory: "embedded-relays",
    subcategoryLabel: "Встраиваемые реле",
    price: 11250,
    rating: 4.7,
    reviewsCount: 312,
    image: images.imgAqaraSwitchT1,
    protocols: ["Zigbee 3.0"],
    functions: ["Управление светом", "Мониторинг"],
    compatibility: ["Aqara Home", "Apple Home"],
    sourceUrl: "https://www.aqara.com",
    specs: { "Нагрузка": "До 2500W", "Нейтраль": "Требуется" },
    primaryFeature: "Скрытый интеллект",
    featureText: "Полностью прячется за вашим любимым дизайнерским выключателем."
  },
  {
    slug: "mean-well-knx-power-supply-640ma",
    name: "Mean Well KNX Power Supply 640mA (KNX-20E-640)",
    brand: "Mean Well",
    group: "b2b",
    collection: "Professional · Power",
    tagline: "Индустриальный блок питания для шины KNX",
    description: "Сердце любой системы KNX. Выдает стабилизированные 30V DC со встроенным дросселем для питания до 64 устройств KNX.",
    category: "bus-systems",
    categoryLabel: "Шинные системы",
    subcategory: "bus-power",
    subcategoryLabel: "Блоки питания для шины",
    price: 67500,
    rating: 5.0,
    reviewsCount: 184,
    image: images.imgMeanWellKnx,
    protocols: ["KNX"],
    functions: ["Питание шины"],
    compatibility: ["KNX TP1"],
    sourceUrl: "https://www.meanwell.com",
    specs: { "Ток": "640mA", "Размер": "3 DIN модуля" },
    primaryFeature: "Легендарная надежность",
    featureText: "Mean Well — золотой стандарт блоков питания для автоматизации."
  },
  {
    slug: "zennio-maxinbox-16-plus",
    name: "Zennio MAXinBOX 16 Plus",
    brand: "Zennio",
    group: "b2b",
    collection: "Professional · KNX",
    tagline: "Многофункциональный актуатор KNX на 16 каналов",
    description: "Ультра-гибкий модуль для щита: 16 релейных выходов, которые конфигурируются как свет, жалюзи или фанкойлы.",
    category: "relays-actuators",
    categoryLabel: "Реле и модули",
    subcategory: "din-relays",
    subcategoryLabel: "Многофункциональные актуаторы",
    price: 202500,
    rating: 4.9,
    reviewsCount: 38,
    image: images.imgZennioMaxinbox,
    protocols: ["KNX"],
    functions: ["Коммутация", "Жалюзи", "Фанкойлы", "Логика"],
    compatibility: ["KNX"],
    sourceUrl: "https://www.zennio.com",
    specs: { "Каналы": "16x 16A C-load", "Логика": "Встроенный модуль" },
    primaryFeature: "Максимальная гибкость",
    featureText: "Настраивается под любую задачу прямо в ETS без дополнительных модулей."
  },
  {
    slug: "wiren-board-7",
    name: "Wiren Board 7",
    brand: "Wiren Board",
    group: "b2b",
    collection: "Professional · Controllers",
    tagline: "Промышленный контроллер для сложной автоматизации",
    description: "Linux-контроллер для умного дома и IoT. Опрашивает сотни устройств по Modbus, имеет встроенный 4G, Wi-Fi и поддерживает SprutHub/HomeAssistant.",
    category: "hubs-networking",
    categoryLabel: "Хабы и серверы",
    subcategory: "multi-protocol-hubs",
    subcategoryLabel: "ПЛК и Серверы",
    price: 135000,
    rating: 4.9,
    reviewsCount: 205,
    image: images.imgWirenBoard7,
    protocols: ["Modbus", "MQTT", "1-Wire", "RS-485", "CAN"],
    functions: ["Контроллер", "Шлюз IoT", "ПЛК"],
    compatibility: ["Home Assistant", "SprutHub", "Node-RED"],
    sourceUrl: "https://wirenboard.com",
    specs: { "Процессор": "Quad-core ARM", "ОС": "Debian Linux" },
    primaryFeature: "Открытая архитектура",
    featureText: "Полный доступ к root, установка любого софта."
  }
`;

content = content.replace(
  'export const productSeeds: ProductSeed[] = [',
  'const productSeeds: ProductSeed[] = ['
);

content = content.replace(
  '];\n\nexport const products: Product[]',
  ',' + newProducts + '\n];\n\nexport const products: Product[]'
);

fs.writeFileSync(p, content, 'utf8');
console.log("SUCCESS!");
